<?php
declare(strict_types=1);

namespace Nimikh\LMS\Pwa;

use Nimikh\LMS\Support\Settings;

/**
 * Phase 3 "PWA first" mobile app: manifest, service worker, offline page, install button.
 * Files are generated by PwaAssets; this class only serves them and adds the <head> tags.
 */
final class Pwa {

	public const QV = 'nimikh_pwa';

	public function register(): void {
		add_action('init', [self::class, 'addRewriteRules']);
		add_filter('query_vars', static fn(array $v): array => array_merge($v, [self::QV]));
		add_action('template_redirect', [$this, 'serve']);
		add_action('wp_head', [$this, 'head'], 1);
		add_action('wp_enqueue_scripts', [$this, 'enqueue']);
		add_shortcode('nimikh_install_button', [$this, 'installButton']);
	}

	public static function addRewriteRules(): void {
		add_rewrite_rule('^nimikh-manifest\.json$', 'index.php?' . self::QV . '=manifest', 'top');
		add_rewrite_rule('^nimikh-sw\.js$', 'index.php?' . self::QV . '=sw', 'top');
		add_rewrite_rule('^nimikh-offline/?$', 'index.php?' . self::QV . '=offline', 'top');
		add_rewrite_rule('^nimikh-icon\.svg$', 'index.php?' . self::QV . '=icon', 'top');
	}

	private function enabled(): bool {
		return (bool) Settings::get('pwa_enabled');
	}

	public function head(): void {
		if (!$this->enabled()) {
			return;
		}
		echo '<link rel="manifest" href="' . esc_url(home_url('/nimikh-manifest.json')) . '">' . "\n";
		echo '<meta name="theme-color" content="#1E4FD8">' . "\n";
		echo '<meta name="mobile-web-app-capable" content="yes">' . "\n";
	}

	public function enqueue(): void {
		if (!$this->enabled()) {
			return;
		}
		wp_enqueue_script('nimikh-pwa', NIMIKH_LMS_URL . 'assets/js/pwa.js', [], NIMIKH_LMS_VERSION, ['in_footer' => true, 'strategy' => 'defer']);
		wp_localize_script('nimikh-pwa', 'NimikhPwa', [
			'sw'    => home_url('/nimikh-sw.js'),
			'scope' => $this->scope(),
		]);
	}

	/** @param array<string, string>|string $atts */
	public function installButton($atts = []): string {
		if (!$this->enabled()) {
			return '';
		}
		wp_enqueue_style('nimikh-tokens');
		wp_enqueue_style('nimikh-player');
		return '<button type="button" class="nk-btn" data-nk-install hidden>' . esc_html__('Install the app', 'nimikh-lms') . '</button>';
	}

	public function serve(): void {
		$what = (string) get_query_var(self::QV);
		if ($what === '') {
			return;
		}
		if (!$this->enabled()) {
			status_header(404);
			exit;
		}
		switch ($what) {
			case 'manifest':
				header('Content-Type: application/manifest+json; charset=utf-8');
				header('Cache-Control: public, max-age=3600');
				echo wp_json_encode(PwaAssets::manifest($this->manifestConfig()), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE); // phpcs:ignore WordPress.Security.EscapeOutput
				break;
			case 'sw':
				header('Content-Type: application/javascript; charset=utf-8');
				header('Service-Worker-Allowed: ' . $this->scope());
				header('Cache-Control: no-cache'); // browsers must always revalidate the worker
				echo PwaAssets::serviceWorker([ // phpcs:ignore WordPress.Security.EscapeOutput -- generated, values json-encoded
					'version'         => NIMIKH_LMS_VERSION,
					'offline_url'     => home_url('/nimikh-offline/'),
					'precache'        => [NIMIKH_LMS_URL . 'assets/css/tokens.css', NIMIKH_LMS_URL . 'assets/css/player.css'],
					'static_prefixes' => [(string) wp_parse_url(NIMIKH_LMS_URL . 'assets/', PHP_URL_PATH)],
				]);
				break;
			case 'offline':
				header('Content-Type: text/html; charset=utf-8');
				header('Cache-Control: public, max-age=86400');
				echo PwaAssets::offlineHtml( // phpcs:ignore WordPress.Security.EscapeOutput -- escaped inside
					get_bloginfo('name'),
					home_url('/'),
					__('You are offline', 'nimikh-lms'),
					__('Check your connection. Your video progress is saved on this device and will sync when you are back online.', 'nimikh-lms'),
					__('Try again', 'nimikh-lms')
				);
				break;
			case 'icon':
				header('Content-Type: image/svg+xml');
				header('Cache-Control: public, max-age=86400');
				echo '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><rect width="512" height="512" rx="96" fill="#1E4FD8"/><text x="256" y="350" font-family="Inter,Arial,sans-serif" font-size="300" font-weight="700" text-anchor="middle" fill="#fff">N</text></svg>';
				break;
			default:
				status_header(404);
		}
		exit;
	}

	private function scope(): string {
		$path = (string) wp_parse_url(home_url('/'), PHP_URL_PATH);
		return $path === '' ? '/' : $path;
	}

	/** @return array{name:string, short_name:string, start_url:string, scope:string, theme_color:string, background_color:string, icon_url:string} */
	private function manifestConfig(): array {
		$name  = get_bloginfo('name') ?: 'Nimikh';
		$start = (string) Settings::get('pwa_start_url');
		$icon  = (string) Settings::get('pwa_icon_url');
		return [
			'name'             => $name,
			'short_name'       => mb_substr($name, 0, 12),
			'start_url'        => $start !== '' ? $start : home_url('/'),
			'scope'            => $this->scope(),
			'theme_color'      => '#1E4FD8',
			'background_color' => '#FFFFFF',
			'icon_url'         => $icon !== '' ? $icon : home_url('/nimikh-icon.svg'),
		];
	}
}
