#!/usr/bin/env bash
# Regenerates cloudflare-realip.conf from Cloudflare's published lists, then tests and reloads nginx.
# Usage: update-cloudflare-ips.sh [target-file]   (default /etc/nginx/snippets/nimikh/cloudflare-realip.conf)
set -euo pipefail
target="${1:-/etc/nginx/snippets/nimikh/cloudflare-realip.conf}"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
{
  echo "# Generated by update-cloudflare-ips.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) from cloudflare.com/ips-v4 and ips-v6."
  for family in ips-v4 ips-v6; do
    curl -fsS --max-time 20 "https://www.cloudflare.com/${family}" | while read -r cidr; do
      [[ "$cidr" =~ ^[0-9a-fA-F:./]+$ ]] || { echo "unexpected line: $cidr" >&2; exit 1; }
      echo "set_real_ip_from ${cidr};"
    done
  done
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} >"$tmp"
[ "$(grep -c '^set_real_ip_from' "$tmp")" -ge 10 ] || { echo "too few ranges, refusing to install" >&2; exit 1; }
install -m 0644 "$tmp" "$target"
nginx -t
systemctl reload nginx
echo "updated $target"
