/* Browser tests for phase 2-3 client code in real Chromium:
 * PWA service worker (generated by PwaAssets.php) incl. offline behaviour, discussion, live classes, reports charts.
 * Run: NODE_PATH=$(npm root -g) node tests/browser/phase23.spec.cjs */
const http = require('http');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const root = path.resolve(__dirname, '../..');
const read = (f) => fs.readFileSync(path.join(root, f));
const php = (code) => execFileSync('php', ['-r', code]).toString();

const swSource = php(`require '${root}/src/Pwa/PwaAssets.php'; echo Nimikh\\LMS\\Pwa\\PwaAssets::serviceWorker(['version'=>'t1','offline_url'=>'/nimikh-offline/','precache'=>['/wp-content/plugins/nimikh-lms/assets/css/tokens.css'],'static_prefixes'=>['/wp-content/plugins/nimikh-lms/assets/']]);`);
const offlineHtml = php(`require '${root}/src/Pwa/PwaAssets.php'; echo Nimikh\\LMS\\Pwa\\PwaAssets::offlineHtml('Nimikh','/','You are offline','Check your connection.','Try again');`);
const manifest = php(`require '${root}/src/Pwa/PwaAssets.php'; echo json_encode(Nimikh\\LMS\\Pwa\\PwaAssets::manifest(['name'=>'Nimikh','short_name'=>'Nimikh','start_url'=>'/','scope'=>'/','theme_color'=>'#1E4FD8','background_color'=>'#fff','icon_url'=>'/nimikh-icon.svg']));`);

const state = { posts: [], joins: [], restHits: 0 };
const i18n = { askPlaceholder: 'Ask…', ask: 'Ask', reply: 'Reply', send: 'Send', delete: 'Delete', hide: 'Hide', unhide: 'Unhide', staff: 'Instructor', hidden: 'Hidden', empty: 'No questions yet.', error: 'err', noLive: 'No live classes.', join: 'Join class', opensSoon: 'Opens soon', liveNow: 'Live now' };
const appCfg = `<script>window.NimikhApp=${JSON.stringify({ restUrl: '/wp-json/nimikh/v1', nonce: 'n', i18n })}</script>`;

const pages = {
  '/': `<!doctype html><meta charset=utf-8><link rel=manifest href=/nimikh-manifest.json><link rel=stylesheet href=/wp-content/plugins/nimikh-lms/assets/css/tokens.css><h1>Home</h1><button data-nk-install hidden>Install</button>
        <script>window.NimikhPwa={sw:'/nimikh-sw.js',scope:'/'}</script><script src=/wp-content/plugins/nimikh-lms/assets/js/pwa.js></script>`,
  '/other/': '<!doctype html><meta charset=utf-8><h1>Other page</h1>',
  '/discussion/': `<!doctype html><meta charset=utf-8><link rel=stylesheet href=/css/tokens.css><link rel=stylesheet href=/css/player.css>${appCfg}
        <section class="nk-discussion" data-lesson="5" data-user="2" data-moderator="MOD"></section><script src=/js/discussion.js></script>`,
  '/live/': `<!doctype html><meta charset=utf-8><link rel=stylesheet href=/css/tokens.css><link rel=stylesheet href=/css/player.css>${appCfg}
        <section class="nk-live" data-course="9"></section><script src=/js/live.js></script>`,
  '/reports/': `<!doctype html><meta charset=utf-8><link rel=stylesheet href=/css/tokens.css><link rel=stylesheet href=/css/reports.css>
        <div id="nk-reports"></div><script>window.NimikhReports={restUrl:'/wp-json/nimikh/v1',nonce:'n'}</script><script src=/js/reports.js></script>`,
};

const retention = Array.from({ length: 12 }, (_, i) => ({ start: i * 10, percent: Math.max(20, 100 - i * 7) }));
const apiRoutes = {
  'GET /wp-json/nimikh/v1/lessons/5/discussion': () => state.posts,
  'GET /wp-json/nimikh/v1/courses/9/live': () => [
    { id: 1, course_id: 9, title: 'Open class', starts_at: '2026-10-12 13:00:00', duration_min: 60, provider: 'jitsi', state: 'open' },
    { id: 2, course_id: 9, title: 'Later class', starts_at: '2026-10-20 13:00:00', duration_min: 60, provider: 'jitsi', state: 'upcoming' },
  ],
  'GET /wp-json/nimikh/v1/me/managed-courses': () => [{ id: 1, title: 'Excel Basics' }],
  'GET /wp-json/nimikh/v1/reports/course/1': () => ({
    summary: { enrolled: 10, completed: 4, completion_rate: 40 },
    learners: [{ name: 'Rafi', lessons_completed: 3, lessons_total: 4, mcq_percent: 80, exam_percent: null, certificate: null }],
    lessons: [{ lesson_id: 1, title: 'Intro <b>bold</b>', retention, questions: [
      { interaction_id: 1, at_second: 30, stem: 'Easy one', learners: 8, first_try_correct: 90 },
      { interaction_id: 2, at_second: 80, stem: 'Hard one', learners: 8, first_try_correct: 25 }] }],
  }),
};

const server = http.createServer((req, res) => {
  const url = req.url.split('?')[0];
  const send = (code, type, body, h = {}) => { res.writeHead(code, { 'Content-Type': type, ...h }); res.end(body); };
  if (url.startsWith('/wp-json/')) state.restHits++;
  if (pages[url]) return send(200, 'text/html', pages[url].replace('MOD', state.moderator ? '1' : '0'));
  if (url === '/nimikh-sw.js') return send(200, 'application/javascript', swSource, { 'Service-Worker-Allowed': '/' });
  if (url === '/nimikh-offline/') return send(200, 'text/html', offlineHtml);
  if (url === '/nimikh-manifest.json') return send(200, 'application/manifest+json', manifest);
  if (url === '/nimikh-icon.svg') return send(200, 'image/svg+xml', '<svg xmlns="http://www.w3.org/2000/svg"/>');
  const assets = { '/wp-content/plugins/nimikh-lms/assets/css/tokens.css': 'assets/css/tokens.css', '/wp-content/plugins/nimikh-lms/assets/js/pwa.js': 'assets/js/pwa.js',
    '/css/tokens.css': 'assets/css/tokens.css', '/css/player.css': 'assets/css/player.css', '/css/reports.css': 'assets/css/reports.css',
    '/js/discussion.js': 'assets/js/discussion.js', '/js/live.js': 'assets/js/live.js', '/js/reports.js': 'assets/js/reports.js' };
  if (assets[url]) return send(200, url.endsWith('.css') ? 'text/css' : 'text/javascript', read(assets[url]));

  let body = ''; req.on('data', (c) => (body += c)); req.on('end', () => {
    const key = `${req.method} ${url}`;
    if (apiRoutes[key]) return send(200, 'application/json', JSON.stringify(apiRoutes[key]()));
    if (key === 'POST /wp-json/nimikh/v1/lessons/5/discussion') {
      const d = JSON.parse(body); state.posts.unshift({ id: state.posts.length + 100, parent_id: d.parent_id, user_id: 2, author: 'Rafi', is_staff: false, body: d.body, status: 'visible', created_at: '2026-10-07 10:00:00', replies: [] });
      return send(201, 'application/json', JSON.stringify(state.posts[0]));
    }
    if (key === 'POST /wp-json/nimikh/v1/live/1/join') { state.joins.push(1); return send(200, 'application/json', JSON.stringify({ url: 'https://meet.jit.si/nimikh-abc', state: 'open' })); }
    send(404, 'application/json', '{"message":"nope"}');
  });
});

(async () => {
  let chromium; try { ({ chromium } = require('playwright')); } catch { ({ chromium } = require(path.join(execFileSync('npm', ['root', '-g']).toString().trim(), 'playwright'))); }
  await new Promise((r) => server.listen(0, r));
  const base = `http://127.0.0.1:${server.address().port}`;
  const browser = await chromium.launch({ executablePath: [process.env.CHROMIUM, '/opt/pw-browsers/chromium'].find((x) => x && require('fs').existsSync(x)), args: ['--no-sandbox'] });
  let failed = 0; const check = (c, l, x = '') => { console.log(`  ${c ? 'ok  ' : 'FAIL'} ${l} ${c ? '' : x}`); if (!c) failed++; };

  // ---------------- PWA ----------------
  console.log('== PWA');
  const ctx = await browser.newContext({ serviceWorkers: 'allow' });
  const pg = await ctx.newPage();
  pg.on('pageerror', (e) => { console.log('  PAGE ERROR', e.message); failed++; });
  await pg.goto(base + '/');
  await pg.evaluate(() => navigator.serviceWorker.ready);
  check(await pg.evaluate(() => navigator.serviceWorker.getRegistration().then((r) => !!r && !!r.active && r.active.state === 'activated')), 'service worker registered and activated');
  await pg.reload();
  check(await pg.evaluate(() => !!navigator.serviceWorker.controller), 'worker controls the page after reload');
  const manifestOk = await pg.evaluate(() => fetch('/nimikh-manifest.json').then((r) => r.json()).then((m) => m.display === 'standalone' && m.icons.length === 1));
  check(manifestOk, 'manifest is valid (standalone, icon)');
  await pg.waitForTimeout(300);
  const keys = await pg.evaluate(async () => { const c = await caches.open('nimikh-t1'); return (await c.keys()).map((r) => new URL(r.url).pathname); });
  check(keys.includes('/nimikh-offline/') && keys.includes('/wp-content/plugins/nimikh-lms/assets/css/tokens.css'), 'offline page and core CSS precached', JSON.stringify(keys));
  await pg.evaluate(() => fetch('/wp-json/nimikh/v1/me/badges').catch(() => {}));
  await pg.waitForTimeout(200);
  const keys2 = await pg.evaluate(async () => (await (await caches.open('nimikh-t1')).keys()).map((r) => new URL(r.url).pathname));
  check(!keys2.some((k) => k.includes('/wp-json/')), 'REST responses are never cached');
  // Really go offline: stop the server (Playwright's offline emulation does not cover service-worker fetches).
  const port = server.address().port;
  server.closeAllConnections(); await new Promise((r) => server.close(r));
  await pg.goto(base + '/other/').catch(() => {});
  check((await pg.locator('h1').innerText().catch(() => '')) === 'You are offline', 'offline navigation shows the offline page');
  const cachedAsset = await pg.evaluate(() => fetch('/wp-content/plugins/nimikh-lms/assets/css/tokens.css').then((r) => r.ok).catch(() => false));
  check(cachedAsset, 'static assets are served from cache while offline');
  const postOffline = await pg.evaluate(() => fetch('/wp-json/nimikh/v1/x', { method: 'POST' }).then(() => 'reached').catch(() => 'failed'));
  check(postOffline === 'failed', 'non-GET requests are not intercepted (fail cleanly offline)');
  await new Promise((r) => server.listen(port, r));
  await pg.goto(base + '/other/');
  check((await pg.locator('h1').innerText()) === 'Other page', 'online navigation goes to the network again');
  await ctx.close();

  // ---------------- discussion ----------------
  console.log('== discussion');
  const dctx = await browser.newContext(); const dp = await dctx.newPage();
  dp.on('pageerror', (e) => { console.log('  PAGE ERROR', e.message); failed++; });
  await dp.goto(base + '/discussion/');
  await dp.waitForSelector('.nk-empty');
  check(await dp.locator('.nk-empty').innerText() === 'No questions yet.', 'empty state shown');
  await dp.locator('textarea').first().fill('Why <img src=x onerror="window.__xss=1"> fails?');
  await dp.getByRole('button', { name: 'Ask' }).click();
  await dp.waitForSelector('.nk-thread__post');
  check(await dp.evaluate(() => window.__xss === undefined) && (await dp.locator('.nk-thread__post p').first().innerText()).includes('<img src=x'), 'posts render as plain text (no HTML injection)');
  check(await dp.locator('.nk-thread__post img').count() === 0, 'no element was created from post text');
  check(await dp.getByRole('button', { name: 'Hide' }).count() === 0 && await dp.getByRole('button', { name: 'Delete' }).count() === 1, 'learner sees Delete on own post but no moderation');
  await dctx.close();
  state.moderator = true;
  const mctx = await browser.newContext(); const mp = await mctx.newPage();
  await mp.goto(base + '/discussion/'); await mp.waitForSelector('.nk-thread__post');
  check(await mp.getByRole('button', { name: 'Hide' }).count() === 1, 'moderator sees Hide');
  await mctx.close();

  // ---------------- live ----------------
  console.log('== live classes');
  const lctx = await browser.newContext(); const lp = await lctx.newPage();
  await lp.goto(base + '/live/'); await lp.waitForSelector('.nk-cert');
  const btns = lp.getByRole('button', { name: 'Join class' });
  check(await btns.count() === 2 && await btns.nth(0).isEnabled() && await btns.nth(1).isDisabled(), 'Join enabled only for the open class');
  await lctx.route('https://meet.jit.si/**', (r) => r.fulfill({ contentType: 'text/html', body: '<h1>room</h1>' }));
  const [popup] = await Promise.all([lctx.waitForEvent('page'), btns.nth(0).click()]);
  await popup.waitForLoadState('domcontentloaded');
  check(popup.url() === 'https://meet.jit.si/nimikh-abc', 'join opens the room link returned by the server', popup.url());
  check(state.joins.length === 1, 'join went through the server (attendance)');
  await lctx.close();

  // ---------------- reports ----------------
  console.log('== reports');
  const rctx = await browser.newContext(); const rp = await rctx.newPage();
  rp.on('pageerror', (e) => { console.log('  PAGE ERROR', e.message); failed++; });
  await rp.goto(base + '/reports/'); await rp.waitForSelector('svg.nkr-chart');
  check((await rp.locator('.nkr-kpi strong').allInnerTexts()).join() === '10,4,40%', 'KPI tiles');
  check(await rp.locator('svg.nkr-chart path.line').count() === 1 && await rp.locator('svg.nkr-chart line.q').count() === 2, 'retention line with 2 question markers');
  check((await rp.locator('svg.nkr-chart').getAttribute('aria-label')).startsWith('Retention for'), 'chart has an accessible label');
  check(await rp.locator('h2', { hasText: 'Intro <b>bold</b>' }).count() === 1 && await rp.locator('h2 b').count() === 0, 'lesson title rendered as text');
  check(await rp.locator('.nkr-hard').count() === 1 && (await rp.locator('.nkr-hard').innerText()).includes('25%'), 'hard question (<50% first try) highlighted');
  const bbox = await rp.locator('svg.nkr-chart').boundingBox();
  check(bbox && bbox.width > 300 && bbox.height > 100, 'chart has a real rendered size');
  await rctx.close();

  console.log(failed ? `\n${failed} failed` : '\nall phase 2-3 browser checks passed');
  await browser.close(); server.close(); process.exit(failed ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(1); });
