<?php
declare(strict_types=1);

namespace Nimikh\LMS\Certificates;

use Nimikh\LMS\Support\RateLimiter;

/**
 * Public, login-free pages:
 *   /verify            search box
 *   /verify/{code}     result (what the QR code points at)
 *   /certificate/{code}/download   owner-only file download
 */
final class VerifyRoute {

	public const QV_VERIFY   = 'nimikh_verify';
	public const QV_CODE     = 'nimikh_code';
	public const QV_DOWNLOAD = 'nimikh_cert_download';

	public function __construct(private CertificateService $service, private CertificateRepository $certs) {}

	public function register(): void {
		add_action('init', [self::class, 'addRewriteRules']);
		add_filter('query_vars', static function (array $vars): array {
			return array_merge($vars, [self::QV_VERIFY, self::QV_CODE, self::QV_DOWNLOAD]);
		});
		add_action('template_redirect', [$this, 'handle']);
	}

	public static function addRewriteRules(): void {
		add_rewrite_rule('^verify/?$', 'index.php?' . self::QV_VERIFY . '=1', 'top');
		add_rewrite_rule('^verify/([A-Za-z0-9\-]+)/?$', 'index.php?' . self::QV_VERIFY . '=1&' . self::QV_CODE . '=$matches[1]', 'top');
		add_rewrite_rule('^certificate/([A-Za-z0-9\-]+)/download/?$', 'index.php?' . self::QV_DOWNLOAD . '=$matches[1]', 'top');
	}

	public static function url(string $code): string {
		return home_url('/verify/' . $code);
	}

	public function handle(): void {
		$download = (string) get_query_var(self::QV_DOWNLOAD);
		if ($download !== '') {
			$this->download($download);
			return;
		}
		if (!get_query_var(self::QV_VERIFY)) {
			return;
		}

		// Search form posts to /verify?code=...
		$posted = isset($_GET['code']) ? sanitize_text_field(wp_unslash((string) $_GET['code'])) : '';
		if ($posted !== '' && get_query_var(self::QV_CODE) === '') {
			$normalised = CodeGenerator::normalise($posted);
			wp_safe_redirect($normalised !== '' ? self::url($normalised) : home_url('/verify/?invalid=1'));
			exit;
		}

		$raw    = (string) get_query_var(self::QV_CODE);
		$result = null;
		if ($raw !== '') {
			if (!RateLimiter::hit('verify', RateLimiter::clientIp(), 30)) {
				status_header(429);
				wp_die(esc_html__('Too many lookups. Try again in a minute.', 'nimikh-lms'), '', ['response' => 429]);
			}
			$result = $this->service->verify($raw);
		}

		if (!headers_sent()) {
			header('X-Robots-Tag: noindex, nofollow');
			// Short public cache so Cloudflare can absorb traffic; revocation shows within 5 minutes.
			header('Cache-Control: public, max-age=300');
			status_header($result && $result['status'] === 'not_found' ? 404 : 200);
		}
		$invalid = isset($_GET['invalid']);
		include NIMIKH_LMS_DIR . 'templates/verify.php';
		exit;
	}

	private function download(string $rawCode): void {
		$code = CodeGenerator::normalise($rawCode);
		$cert = $code === '' ? null : $this->certs->findByCode($code);
		$user = get_current_user_id();

		$allowed = $cert && $user && ($cert['user_id'] === $user || current_user_can(\Nimikh\LMS\Support\Roles::CAP_MANAGE));
		if (!$allowed) {
			wp_die(esc_html__('Certificate not found.', 'nimikh-lms'), '', ['response' => 404]);
		}
		if ($cert['status'] !== CertificateRepository::STATUS_VALID) {
			wp_die(esc_html__('This certificate has been revoked.', 'nimikh-lms'), '', ['response' => 410]);
		}
		$bytes = $cert['pdf_key'] ? CertificateStorage::get($cert['pdf_key']) : null;
		if ($bytes === null) {
			wp_die(esc_html__('Your certificate is still being prepared. Check again in a minute.', 'nimikh-lms'), '', ['response' => 202]);
		}

		$isPdf = str_ends_with((string) $cert['pdf_key'], '.pdf');
		nocache_headers();
		header('Content-Type: ' . ($isPdf ? 'application/pdf' : 'text/html; charset=utf-8'));
		if ($isPdf) {
			header('Content-Disposition: attachment; filename="certificate-' . $cert['code'] . '.pdf"');
		}
		header('X-Content-Type-Options: nosniff');
		echo $bytes; // phpcs:ignore WordPress.Security.EscapeOutput -- file generated by renderer from escaped values
		exit;
	}
}
